meta_product_name: "Inventory"
meta_title: "Inventory"
meta_description: "Inventory"
meta_image: "components/og-image-menu.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
